/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Class.Koneksi;
import UI.Pembelian_Transaksi;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Pembelian_KotakHistoriBarang extends javax.swing.JFrame {

    /**
     * Creates new form Pembelian_KotakHistoriBarang
     */
    static String Kode = "";

    public static Pembelian_KotakHistoriBarang obj = null;

    Pembelian_KotakHistoriBarang() {
        initComponents();
        this.setVisible(true);

    }

    public void History(String Kode) {
        try {
            String sql = "SELECT pembelian.no_faktur_pembelian,pembelian.tgl_pembelian,pembelian.discon_persen,pembelian.discon_rp,detail_pembelian.no_faktur_pembelian,"
                    + "detail_pembelian.jumlah_barang,detail_pembelian.kode_barang,detail_pembelian.harga_pembelian "
                    + ",detail_pembelian.harga_asli_pakai,detail_pembelian.harga_asli ,detail_pembelian.discon_rp , "
                    + "detail_pembelian.jumlah_barang FROM pembelian,detail_pembelian "
                    + "WHERE pembelian.no_faktur_pembelian =detail_pembelian.no_faktur_pembelian "
                    + "AND detail_pembelian.kode_barang = '" + Kode + "' "
                    + "order BY pembelian.no_faktur_pembelian DESC LIMIT 1";
            System.out.println(sql);
            java.sql.Connection conn = (Connection) Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            //  System.out.println(sql);
            while (res.next()) {
                txt_faktur.setText(res.getString("no_faktur_pembelian"));
                txt_tanggal.setText(res.getString("tgl_pembelian"));
                txt_beli.setText(res.getString("harga_pembelian"));
                txt_beli2.setText(res.getString("harga_asli_pakai"));
                txt_rata.setText(res.getString("harga_asli"));
                txt_disc.setText(res.getString("discon_rp"));
                txt_netto.setText(res.getString("jumlah_barang"));
                System.out.println("ini data Faktur = " + res.getString("no_faktur_pembelian"));
                System.out.println("ini data beli = " + res.getString("harga_pembelian"));
                System.out.println("ini data netto = " + res.getString("jumlah_barang"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror" + e);
        }
    }

    Pembelian_KotakHistoriBarang(String Kode) {
        initComponents();
        this.Kode = Kode;
        System.out.println("Kode = " + this.Kode);
        History(Kode);

    }

    private static Pembelian_KotakHistoriBarang getObj(int i) {

            System.out.println("Get obj obj obj = " + obj);
        if (obj == null) {
            System.out.println("Get obj Kode = " + Kode);
            obj = new Pembelian_KotakHistoriBarang(Kode);
        }
        return obj;
    }

    public void loadDisable() {
        txt_beli.setEnabled(false);
        txt_beli2.setEnabled(false);
        txt_disc.setEnabled(false);
        txt_faktur.setEnabled(false);
        txt_netto.setEnabled(false);
        txt_rata.setEnabled(false);
        txt_tanggal.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHistori = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_faktur = new javax.swing.JTextField();
        txt_tanggal = new javax.swing.JTextField();
        txt_beli = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_beli2 = new javax.swing.JTextField();
        txt_rata = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_disc = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_netto = new javax.swing.JTextField();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(330, 170));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(601, 132));
        setSize(new java.awt.Dimension(601, 132));
        getContentPane().setLayout(null);

        PanelHistori.setBackground(new java.awt.Color(153, 0, 0));
        PanelHistori.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        PanelHistori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelHistoriMouseClicked(evt);
            }
        });
        PanelHistori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PanelHistoriKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 204));
        jLabel14.setText("Faktur");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 204));
        jLabel15.setText("Tanggal");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 204));
        jLabel16.setText("Hrg Beli");

        txt_faktur.setBackground(new java.awt.Color(255, 255, 204));
        txt_faktur.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_faktur.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txt_tanggal.setBackground(new java.awt.Color(255, 255, 204));
        txt_tanggal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_tanggal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txt_beli.setBackground(new java.awt.Color(255, 255, 204));
        txt_beli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_beli.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 204));
        jLabel20.setText("Hrg Rata2");

        txt_beli2.setBackground(new java.awt.Color(255, 255, 204));
        txt_beli2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_beli2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txt_rata.setBackground(new java.awt.Color(255, 255, 204));
        txt_rata.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_rata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 204));
        jLabel21.setText("Hrg Beli");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 204));
        jLabel22.setText("Disc");

        txt_disc.setBackground(new java.awt.Color(255, 255, 204));
        txt_disc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_disc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 204));
        jLabel23.setText("Netto Beli");

        txt_netto.setBackground(new java.awt.Color(255, 255, 204));
        txt_netto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_netto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout PanelHistoriLayout = new javax.swing.GroupLayout(PanelHistori);
        PanelHistori.setLayout(PanelHistoriLayout);
        PanelHistoriLayout.setHorizontalGroup(
            PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHistoriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_faktur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_rata, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_disc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_netto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_beli2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PanelHistoriLayout.setVerticalGroup(
            PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHistoriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(PanelHistoriLayout.createSequentialGroup()
                        .addComponent(txt_rata, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_beli2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_disc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_netto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(PanelHistoriLayout.createSequentialGroup()
                        .addGroup(PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_faktur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel22))))
                .addGap(5, 5, 5))
        );

        getContentPane().add(PanelHistori);
        PanelHistori.setBounds(0, 0, 606, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelHistoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHistoriMouseClicked
        dispose();
    }//GEN-LAST:event_PanelHistoriMouseClicked

    private void PanelHistoriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PanelHistoriKeyPressed

    }//GEN-LAST:event_PanelHistoriKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian_KotakHistoriBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian_KotakHistoriBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian_KotakHistoriBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian_KotakHistoriBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian_KotakHistoriBarang().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHistori;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JTextField txt_beli;
    private javax.swing.JTextField txt_beli2;
    private javax.swing.JTextField txt_disc;
    private javax.swing.JTextField txt_faktur;
    private javax.swing.JTextField txt_netto;
    private javax.swing.JTextField txt_rata;
    private javax.swing.JTextField txt_tanggal;
    // End of variables declaration//GEN-END:variables
}
